name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    name: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file
        uses: ChenjxJames/SFTP-Deploy-Action@v1.3.2
        with:
          server: '104.155.230.1'
          username: 'gaganbabber'
          ssh_private_key: ${{ secrets.tw_staging }}
          local_path: '../../../demo_ci_cd'
          remote_path: '/home/gaganbabber/rails/staging/'
          args: '-o ConnectTimeout=5'