name: Deploy to Shared Hosting

env:
  USERNAME: 'gaganbabber'
  SERVER_IP: '104.155.230.1'

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TW_STAGINGGG }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: |
          ssh-keyscan ${USERNAME} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${USERNAME}@${SERVER_IP} 'cd /home/gaganbabber/rails/staging/demo_ci_cd/demo_ci_cd && git pull origin main'
