name: Deploy Code to Server...

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_DIR: /home/gaganbabber/rails/staging/

    steps:
      - name: Checkout code.
        uses: actions/checkout@v1

      - name: 📂 Sync files
        uses: kartiktailwebs/demo_ci_cd@main
        with:
          ssh-private-key: /Users/kartik/.ssh/tw_staging
          ssh-username: gaganbabber
          ssh-host: 104.155.230.1
          ssh-port: 22
