name: Deploy Code to Server 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy Code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH key :)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.tw_staging }}" > ~/.ssh/tw_stg
          chmod 600 ~/.ssh/tw_stg

      - name: Connected To SSH Server & Deploy 🚀
        run: |
          ssh -i ~/.ssh/tw_staging -o StrictHostKeyChecking=no gaganbabber@104.155.230.1 'cd /home/gaganbabber/rails/staging/demo_ci_cd && sh runner-script.sh'