name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    env:
      SERVER_DIR: /home/gaganbabber/rails/staging/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: ChenjxJames/SFTP-Deploy-Action@v1.3.2
        with:
          server: '104.155.230.1'
          username: 'gaganbabber'
          ssh_private_key: ${{ secrets.tw_staging }}
          local_path: './*'
          remote_path: '/home/gaganbabber/rails/staging/demo_ci_cd/'
          args: '-o ConnectTimeout=5'