name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          host: 104.155.230.1
          username: gaganbabber
          key: ${{ secrets.tw_staging }}
          port: 22
          server-dir: /home/gaganbabber/rails/staging/