name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    name: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file
        uses: ruby/setup-ruby@v1
        with:
          server: '104.155.230.1'
          username: 'gaganbabber'
          ssh_private_key: ${{ secrets.tw_staging }}
          local_path: '../../*'
          remote_path: '/home/gaganbabber/rails/staging/demo_ci_cd/'
          args: '-o ConnectTimeout=5'