name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: '104.155.230.1'
          username: 'gaganbabber'
          key: ${{ secrets.tw_staging }}

      - name: SFTP Transfer
        uses: appleboy/scp-action@master
        with:
          local: ./*
          remote: /home/gaganbabber/rails/staging/demo_ci_cd/