name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to SSH server and deploy
        run: |
          ssh -i ~/.ssh/tw_staging -o StrictHostKeyChecking=no gaganbabber@104.155.230.1