name: Deploy Code to Server

env:
  USERNAME: 'gaganbabber'
  SERVER_IP: '104.155.230.1'
  SSH_PRIVATE_KEY: ${{ secrets.tw_staging }}
  LOCAL_PATH: './*'
  REMOTE_PATH: '/home/gaganbabber/rails/staging/demo_ci_cd/'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    env:
      SERVER_DIR: /home/gaganbabber/rails/staging/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: ChenjxJames/SFTP-Deploy-Action@v1.3.2
        with:
          server: '${SERVER_IP}'
          username: '${USERNAME}'
          ssh_private_key: ${SSH_PRIVATE_KEY}
          local_path: '${LOCAL_PATH}'
          remote_path: '${REMOTE_PATH}'
          args: '-o ConnectTimeout=5'
