name: Deploy Code to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_DIR: /home/gaganbabber/rails/staging/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.tw_staging }}
          ssh-username: gaganbabber
          ssh-host: 104.155.230.1
          ssh-port: 22

      - name: Deploy to Server
        run: |
          # Add your deployment commands here, e.g., rsync, scp, etc.
          # Example using rsync:
          rsync -r --delete /Users/kartik/Projects/4_Ruby/0_study/2_Rails_Projects_Demo/demo-ci-cd ${{ env.SERVER_DIR }}
